apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: persistent-storage
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: docker.io/hostpath
reclaimPolicy: Retain # default value is Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
