\set ON_ERROR_STOP 1
begin;

SET CONSTRAINTS ALL DEFERRED;

insert into "globalData" ("extras", "id") values ('{"dbReadOnly":false}', 'main');
insert into "users" ("displayName", "edits", "id", "joinDate", "lastEditAt", "permissionGroups", "photoURL") values ('[system]', 0, 'DM_SYSTEM_000000000001', 1669005049707, NULL, '{"basic":true,"verified":true,"mod":true,"admin":true}', NULL);
insert into "userHiddens" ("addToStream", "email", "extras", "id", "providerData") values (false, 'debatemap@gmail.com', '{}', 'DM_SYSTEM_000000000001', '{}');
insert into "accessPolicies" ("createdAt", "creator", "id", "name", "permissions", "permissions_userExtends") values (1669005049708, 'DM_SYSTEM_000000000001', '4jVSfi1dTS6lCF2j1vy1mA', 'Public, ungoverned (standard)', '{"terms":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"medias":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"maps":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"nodes":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":0,"minApprovalPercent":0},"addPhrasing":{"minApprovals":0,"minApprovalPercent":0}},"nodeRatings":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}}}', '{}');
insert into "accessPolicies" ("createdAt", "creator", "id", "name", "permissions", "permissions_userExtends") values (1669005049708, 'DM_SYSTEM_000000000001', 'xqLi-eDRQU-YjTAK-4YYUA', 'Public, governed (standard)', '{"terms":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"medias":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"maps":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"nodes":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":0,"minApprovalPercent":0},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"nodeRatings":{"access":true,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}}}', '{}');
insert into "accessPolicies" ("createdAt", "creator", "id", "name", "permissions", "permissions_userExtends") values (1669005049709, 'DM_SYSTEM_000000000001', 'uyadhsxFRXagUMc8rUbjmg', 'Private, governed (standard)', '{"terms":{"access":false,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"medias":{"access":false,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"maps":{"access":false,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"nodes":{"access":false,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}},"nodeRatings":{"access":false,"modify":{"minApprovals":-1,"minApprovalPercent":-1},"delete":{"minApprovals":-1,"minApprovalPercent":-1},"vote":{"minApprovals":-1,"minApprovalPercent":-1},"addPhrasing":{"minApprovals":-1,"minApprovalPercent":-1}}}', '{}');
insert into "maps" ("accessPolicy", "createdAt", "creator", "defaultExpandDepth", "editedAt", "editors", "edits", "extras", "id", "name", "rootNode") values ('xqLi-eDRQU-YjTAK-4YYUA', 1669005049709, 'DM_SYSTEM_000000000001', 3, 1669005049709, '{}', 0, '{}', 'GLOBAL_MAP_00000000001', 'Global', 'GLOBAL_ROOT_0000000001');
insert into "nodes" ("accessPolicy", "c_currentRevision", "createdAt", "creator", "extras", "id", "rootNodeForMap", "type") values ('xqLi-eDRQU-YjTAK-4YYUA', 't5lMQlrCRxqdGbcPGXfAgA', 1669005049709, 'DM_SYSTEM_000000000001', '{}', 'GLOBAL_ROOT_0000000001', 'GLOBAL_MAP_00000000001', 'category');
insert into "nodeRevisions" ("attachments", "createdAt", "creator", "id", "node", "phrasing") values ('{}', 1669005049709, 'DM_SYSTEM_000000000001', 't5lMQlrCRxqdGbcPGXfAgA', 'GLOBAL_ROOT_0000000001', '{"text_base":"Root","terms":[]}');

commit;